export const GET_NEW_BOOKS_START = 'GET_NEW_BOOKS_START';
export const GET_NEW_BOOKS_SUCCESS = 'GET_NEW_BOOKS_SUCCESS';
export const GET_NEW_BOOKS_END = 'GET_NEW_BOOKS_END';
export const GET_NEW_BOOKS_FAIL = 'GET_NEW_BOOKS_FAIL';

export const GET_BOOK_DETAILS_START = 'GET_BOOK_DETAILS_START';
export const GET_BOOK_DETAILS_SUCCESS = 'GET_BOOK_DETAILS_SUCCESS';
export const GET_BOOK_DETAILS_END = 'GET_BOOK_DETAILS_END';
export const GET_BOOK_DETAILS_FAIL = 'GET_BOOK_DETAILS_FAIL';

export const ADD_TO_CART = 'ADD_TO_CART';